- hosts: bamboo-agents
  remote_user: ubuntu
  become: true

  tasks:
    - name: add repository key
      apt_key:
        id: 58118E89F3A912897C070ADBF76221572C52609D
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        state: present

    - name: add repository
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
        state: present

    - name: create data directory
      file:
        path: /mnt/storage/docker
        state: directory

    - name: symlink data directory
      file:
        src: /mnt/storage/docker
        dest: /var/lib/docker
        state: link

    - name: install docker
      apt:
        name: docker-engine
        update_cache: yes

    - name: copy service script
      copy:
        src: files/docker.service
        dest: /etc/systemd/system/docker.service

    - name: enable and start docker service
      systemd:
        name: docker
        enabled: yes
        daemon_reload: yes
        state: restarted
