- hosts: bamboo-agents
  remote_user: ubuntu
  gather_facts: false
  become: true

  tasks:
    - name: disable net.ipv6.conf.all.disable_ipv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        sysctl_set: yes

    - name: disable net.ipv6.conf.default.disable_ipv6
      sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: 1
        sysctl_set: yes

    - name: disable net.ipv6.conf.lo.disable_ipv6
      sysctl:
        name: net.ipv6.conf.lo.disable_ipv6
        value: 1
        sysctl_set: yes
