- hosts: bamboo-agents
  remote_user: ubuntu
  become: true

  tasks:
    - name: add repository key
      apt_key:
        id: 58118E89F3A912897C070ADBF76221572C52609D
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        state: present

    - name: add repository
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
        state: present

    - name: install docker
      apt:
        name: docker-engine
        update_cache: yes

    - name: restart docker service
      service:
        name: docker
        state: restarted
