- hosts: bamboo-agents
  remote_user: ubuntu
  gather_facts: false
  become: true

  tasks:
    - name: update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes

    - name: reboot
      shell: sleep 5 && reboot now
      async: 1
      poll: 0
